// <auto-generated />
namespace Jewellery.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updatingforiegnkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updatingforiegnkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201707181025066_Updating foriegn key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
